const products = [
    {
        id: 1,
        title: 'Colar Elegante',
        subtitle: 'Colar elegante com pingentes de coração e brilho sutil',
        description: 'O colar elegante com pingentes de coração é uma peça refinada e encantadora que combina beleza e significado. Este exuberante acessório é meticulosamente trabalhado para criar uma aparência sofisticada e atemporal. O colar em si é composto por uma delicada corrente, muitas vezes feita de materiais de alta qualidade, como ouro, prata ou platina, conferindo-lhe um brilho sutil e uma durabilidade notável. A corrente é elegantemente projetada para se ajustar graciosamente ao redor do pescoço, proporcionando um toque de elegância que complementa qualquer estilo ou ocasião. Seja como uma declaração de amor ou simplesmente como um toque elegante para realçar a beleza, o colar com pingente de coração é uma escolha sublime que une estilo, sofisticação e significado sentimental em uma única peça de joia.',
        price: 620.00,
        poster: './imgs/colares/c2.png',
        category: 'colar',
    },
    {
        id: 2,
        title: 'Brinco Prata Luxo',
        subtitle: 'Brinco de prata com topázios e brilho intenso',
        description:'Explore o seu estilo com elegância e sofisticação usando nosso "Brinco de Prata Luxo". Este deslumbrante par de brincos é confeccionado com prata de alta qualidade, proporcionando durabilidade e brilho notável. Os topázios cuidadosamente cravados conferem um toque de glamour, capturando a luz de maneira deslumbrante e garantindo um brilho intenso que não passará despercebido. Seu design delicado e contemporâneo faz com que esses brincos sejam a escolha perfeita para qualquer ocasião, desde eventos formais até momentos mais descontraídos. Além de sua beleza estonteante, esses brincos oferecem conforto durante todo o dia, garantindo que você esteja sempre impecável. Adicione um toque de brilho e classe ao seu visual com o "Brinco de Prata Luxo" - a escolha ideal para quem busca um acessório que equilibra estilo e elegância com maestria. Encomende o seu agora e eleve a sua coleção de joias a um novo patamar de refinamento.',
        price: 480.00,
        poster: './imgs/brincos/b1.png',
        category: 'brinco',
    },
    {
        id: 3,
        title: 'Anel Solitário de Luxo',
        subtitle: 'Anel solitário de luxo com brilho em prata 925',
        description:'Descubra a expressão máxima de luxo com nosso "Anel Solitário de Luxo em Prata 925". Este anel excepcional combina a beleza intemporal da prata fina 925 com o esplendor de um solitário brilhante, criando uma peça que é ao mesmo tempo deslumbrante e elegante. O design cuidadosamente elaborado destaca o brilho singular da gema central, que reflete a luz de maneira cativante, enchendo o ambiente com uma luminosidade única. A prata 925 confere ao anel uma qualidade excepcional, assegurando durabilidade e um acabamento impecável. Seja como uma declaração de compromisso, presente especial ou simplesmente para elevar seu estilo cotidiano, este anel solitário é a escolha perfeita. Sua elegância discreta e design atemporal fazem dele uma joia versátil que pode ser apreciada em todas as ocasiões. Viva a experiência de usar uma peça que reflete seu gosto refinado e celebra a singularidade do momento. Eleve seu estilo com o "Anel Solitário de Luxo em Prata 925" – uma joia que transcende o tempo com sua beleza clássica e atemporal. Adquira o seu agora e adicione um toque de luxo à sua coleção de acessórios.',
        price: 720.00,
        poster: './imgs/aneis/anel9.png',
        category: 'anel',
    },
    {
        id: 4,
        title: 'Pingente Personalizado',
        subtitle: 'Pingente em prata topázios personalizável para colar',
        description: 'Explore a arte da personalização e adicione um toque único à sua coleção de joias com nosso "Pingente Personalizável em Prata com Topázios para Colar". Este pingente excepcional é mais do que uma peça de joia; é uma expressão personalizada do seu estilo e individualidade. Confeccionado em prata de alta qualidade, o pingente exala elegância e durabilidade. A beleza dos topázios cuidadosamente cravados adiciona um toque de brilho sutil, capturando a luz de maneira encantadora. O destaque verdadeiramente especial deste pingente é a oportunidade de personalização. Adicione um toque pessoal escolhendo um design único, uma inicial ou até mesmo uma data significativa. Seja para celebrar uma ocasião especial ou como um presente pensado, este pingente personalizável é uma maneira extraordinária de eternizar memórias e expressar sua singularidade. Use-o com um colar de sua escolha para criar uma peça única que conte sua história. Com o "Pingente Personalizável em Prata com Topázios para Colar", você não está apenas usando uma joia, está usando uma lembrança personalizada e preciosa. Encomende agora e dê um toque pessoal à sua coleção de acessórios.',
        price: 330.00,
        poster: './imgs/pingentes/p1.png',
        category: 'pingente',
    },
    {
        id: 5,
        title: 'Pulseira Glamourosa',
        subtitle: 'Pulseira em prata e topázios, elegante com 20cm',
        description: 'Eleve sua sofisticação com a "Pulseira Elegante em Prata e Topázios", uma joia que combina elegância e brilho de forma excepcional. Confeccionada em prata de alta qualidade, esta pulseira destaca-se pela harmoniosa combinação de seus elos delicados e topázios deslumbrantes. Com um comprimento de 20cm, ela envolve seu pulso com graça e estilo. Seja para ocasiões formais ou para adicionar um toque de refinamento ao seu visual diário, esta pulseira é a escolha perfeita. Deixe-se envolver pela beleza atemporal da prata e pelos centelhantes topázios, fazendo desta pulseira uma expressão luminosa da sua elegância única. Adquira agora e realce sua coleção de joias com esse símbolo de sofisticação.',
        price: 420.00,
        poster: './imgs/pulseiras/pulseira.png',
        category: 'pulseira',
    },
    {
        id: 6,
        title: 'Anel Solitário Deluxe',
        subtitle: 'Anel solitário deluxe em prata 925',
        description:'Experimente a essência do luxo com o "Anel Solitário Deluxe em Prata 925". Esta peça extraordinária é uma celebração da elegância atemporal, combinando a qualidade distinta da prata 925 com o brilho singular de um solitário. O design meticuloso destaca a gema central, irradiando sofisticação e refinamento. Este anel solitário é mais do que uma joia, é uma declaração de estilo e graciosidade, perfeito para elevar qualquer ocasião. Seja como uma expressão de compromisso, um presente especial ou um mimo para si mesmo, o "Anel Solitário Deluxe em Prata 925" é uma escolha sublime que transcende tendências, oferecendo uma beleza duradoura e inigualável. Adquira o seu agora e envolva-se na aura luxuosa desta joia excepcional.',
        price: 720.00,
        poster: './imgs/aneis/a3.png',
        category: 'anel',
    },
    {
        id: 7,
        title: 'Pingente Charmoso',
        subtitle: 'Pingente charmoso em prata topázios para colar',
        description:'Adorne-se com encanto e distinção com o "Pingente Charmoso em Prata com Topázios para Colar". Esta deslumbrante peça de joalheria combina a elegância da prata com a delicadeza dos topázios, criando um pingente que irradia charme e sofisticação. Seu design cativante destaca-se pela harmonia entre os detalhes finamente trabalhados e a cintilância dos topázios, conferindo à peça um brilho sutil e irresistível. Perfeito para ser usado com um colar de sua escolha, este pingente charmoso adiciona um toque de estilo único e atemporal a qualquer conjunto. Celebre sua feminilidade com esta joia exuberante e versátil. Adquira agora e deixe-se envolver pela beleza cativante do "Pingente Charmoso em Prata com Topázios para Colar"',
        price: 310.00,
        poster: './imgs/pingentes/p2.png',
        category: 'pingente',
    },
    {
        id: 8,
        title: 'Colar Quadricular Radiante',
        subtitle: 'Colar quadricular radiante com brilho intenso',
        description:'Transforme seu visual com o "Colar Quadricular Radiante com Brilho Intenso", uma peça de destaque que combina design moderno com um brilho inigualável. Este colar exibe uma trama quadricular cuidadosamente elaborada, conferindo-lhe um charme contemporâneo e sofisticado. Acentuado por um brilho intenso, este acessório adiciona um toque de luminosidade cativante ao seu decote, tornando-o perfeito para qualquer ocasião. Seja para um evento especial ou para elevar o seu estilo cotidiano, este colar radiante é a escolha perfeita para quem busca uma joia que equilibra elegância e modernidade. Adquira agora e ilumine o seu visual com o esplendor do "Colar Quadricular Radiante com Brilho Intenso".',
        price: 560.00,
        poster: './imgs/colares/colar9.png',
        category: 'colar',
    },
    {
        id: 9,
        title: 'Pulseira Sofisticada',
        subtitle: 'Pulseira sofisticada em prata e topázios, 20cm',
        description:'Evoque a sofisticação com a "Pulseira Sofisticada em Prata e Topázios, 20cm", uma joia que harmoniza a beleza intemporal da prata com o brilho cativante dos topázios. Com seu comprimento de 20cm, essa pulseira envolve o pulso com elegância e estilo refinado. Os detalhes finamente trabalhados e os topázios estrategicamente posicionados conferem um toque de luxo a esta peça, tornando-a ideal para complementar tanto looks formais quanto informais. Adquira agora e adicione um toque de brilho e refinamento à sua coleção de joias com esta "Pulseira Sofisticada em Prata e Topázios".',
        price: 410.00,
        poster: './imgs/pulseiras/pulseira1.png',
        category: 'pulseira',
    },
    {
        id: 10,
        title: 'Brinco Luxuoso',
        subtitle: 'Brinco luxuoso de prata com topázios e brilho',
        description:'Eleve o seu glamour com o "Brinco Luxuoso de Prata com Topázios e Brilho". Esta joia exuberante combina a nobreza da prata com a deslumbrante cintilação dos topázios, criando um par de brincos que é sinônimo de elegância refinada. O design luxuoso destaca-se pela harmonia entre o brilho intenso dos topázios e a sofisticação atemporal da prata. Seja para uma ocasião especial ou para adicionar um toque de luxo ao seu visual diário, estes brincos são a escolha perfeita. Sinta-se imersa na aura de opulência destes brincos luxuosos e permita que eles realcem a sua beleza com um brilho irresistível. Adquira agora e experimente o requinte inigualável do "Brinco Luxuoso de Prata com Topázios e Brilho".',
        price: 480.00,
        poster: './imgs/brincos/brinco1.png',
        category: 'brinco',
    },
    {
        id: 11,
        title: 'Pulseira Elegância',
        subtitle: 'Pulseira em prata e topázios, 20cm de elegância',
        description: 'Deslumbre com a "Pulseira em Prata e Topázios, 20cm de Elegância". Esta pulseira exala sofisticação, combinando a pureza da prata com o brilho cativante dos topázios. Com seu comprimento de 20cm, a pulseira envolve o pulso com graciosidade, acrescentando um toque de elegância refinada. Os topázios estrategicamente cravejados conferem um charme sutil, destacando-se como símbolos de refinamento e beleza. Seja para um evento especial ou para elevar o seu estilo cotidiano, esta pulseira é a escolha perfeita para quem busca uma joia que une estilo e elegância de maneira única. Adquira agora e deixe-se envolver pela beleza atemporal da "Pulseira em Prata e Topázios, 20cm de Elegância".',
        price: 410.00,
        poster: './imgs/pulseiras/pulseira2.png',
        category: 'pulseira',
    },
    {
        id: 12,
        title: 'Pingente Deluxe',
        subtitle: 'Pingente deluxe em prata topázios para colar',
        description: 'Adicione um toque de requinte ao seu visual com o "Pingente Deluxe em Prata com Topázios para Colar". Esta joia exuberante é uma expressão de luxo e sofisticação, unindo a pureza da prata ao brilho deslumbrante dos topázios. O design deluxe deste pingente destaca-se pela sua elegância atemporal e pelos detalhes finamente trabalhados. Seja usado como um ponto focal em um colar ou combinado com outras peças, este pingente é a escolha ideal para quem busca uma joia que emana estilo e distinção. Adquira agora e permita que o "Pingente Deluxe em Prata com Topázios para Colar" eleve o seu visual a novos patamares de elegância.',
        price: 310.00,
        poster: './imgs/pingentes/p3.png',
        category: 'pingente',
    },
    {
        id: 13,
        title: 'Colar Estiloso',
        subtitle: 'Colar estiloso com pingente quadricular e brilho',
        description: 'Faça uma declaração de estilo com o "Colar Estiloso com Pingente Quadricular e Brilho". Este colar cativante combina moda e sofisticação, apresentando um pingente quadricular que incorpora um brilho encantador. O design estiloso deste colar é marcado pela fusão de linhas modernas e elegância clássica, proporcionando um toque contemporâneo à sua coleção de joias. Seja para realçar seu visual casual ou adicionar um elemento de destaque a uma ocasião especial, este colar é a escolha perfeita. Adquira agora e deixe que o "Colar Estiloso com Pingente Quadricular e Brilho" eleve o seu estilo a novas alturas de glamour e sofisticação.',
        price: 580.00,
        poster: './imgs/colares/colar1.png',
        category: 'colar',
    },
    {
        id: 14,
        title: 'Brinco Glamour',
        subtitle: 'Brinco de prata topázios e brilho, pura elegância',
        description: 'Adorne-se com pura elegância usando o "Brinco de Prata com Topázios e Brilho". Este par de brincos é uma celebração da refinada simplicidade, combinando a pureza da prata com a deslumbrante cintilação dos topázios. O design cuidadosamente elaborado destaca-se pela sua sofisticação atemporal, conferindo um toque de classe a qualquer look. Seja para uma ocasião especial ou para elevar o seu estilo diário, estes brincos são a escolha perfeita para quem busca uma joia que harmoniza elegância e brilho de maneira sublime. Adquira agora e permita que o "Brinco de Prata com Topázios e Brilho" acrescente um toque de puro requinte à sua coleção de acessórios.',
        price: 490.00,
        poster: './imgs/brincos/brinco2.png',
        category: 'brinco',
    },
    {
        id: 15,
        title: 'Anel Radiante',
        subtitle: 'Anel radiante de brilho solitário em prata 925',
        description: 'Deixe-se envolver pela luminosidade radiante do "Anel Solitário de Brilho em Prata 925". Este anel é uma expressão de singularidade e elegância, unindo a beleza intemporal da prata 925 ao brilho solitário que captura a luz de maneira envolvente. O design radiante destaca a gema central com um esplendor cativante, tornando este anel uma peça que brilha tanto em ocasiões especiais quanto no dia a dia. Adquira agora e permita que o "Anel Radiante de Brilho Solitário em Prata 925" eleve seu estilo a novos patamares de sofisticação e luminosidade.',
        price: 740.00,
        poster: './imgs/aneis/anel1.png',
        category: 'anel',
    },
    {
        id: 16,
        title: 'Colar Quadricular Brilhante',
        subtitle: 'Colar quadricular brilhante com pingente',
        description: 'Faça uma declaração de estilo com o "Colar Quadricular Brilhante com Pingente". Este colar encantador combina um design quadricular moderno com um brilho luminoso, criando uma peça que é ao mesmo tempo contemporânea e elegante. O pingente adiciona um toque especial, destacando-se no padrão quadricular com um brilho cativante. Seja para realçar seu visual casual ou adicionar um toque de sofisticação a uma ocasião especial, este colar é a escolha perfeita. Adquira agora e permita que o "Colar Quadricular Brilhante com Pingente" eleve o seu estilo a novas alturas de glamour e modernidade.',
        price: 590.00,
        poster: './imgs/colares/colar2.png',
        category: 'colar',
    },
    {
        id: 17,
        title: 'Brinco Chique',
        subtitle: 'Brinco chique de prata topázios e brilho',
        description: 'Emane um charme irresistível com o "Brinco Chique de Prata com Topázios e Brilho". Este par de brincos é uma fusão de elegância e estilo, combinando a sofisticação da prata com o brilho deslumbrante dos topázios. O design chique destaca-se pela sua simplicidade refinada, adicionando um toque de glamour discreto ao seu visual. Seja para uma ocasião especial ou para elevar o seu estilo diário, estes brincos são a escolha perfeita para quem busca uma joia que harmoniza sofisticação e brilho de maneira excepcional. Adquira agora e permita que o "Brinco Chique de Prata com Topázios e Brilho" acrescente um toque de puro requinte à sua coleção de acessórios.',
        price: 500.00,
        poster: './imgs/brincos/brinco3.png',
        category: 'brinco',
    },
    {
        id: 18,
        title: 'Anel Prata Fina',
        subtitle: 'Anel de prata fina com brilho solitário em 925',
        description: 'Deixe a beleza simples e elegante falar por si com o "Anel de Prata Fina com Brilho Solitário em 925". Esta peça única une a pureza da prata 925 ao encanto intemporal de um brilho solitário, criando uma joia que é ao mesmo tempo refinada e sofisticada. O design minimalista destaca a gema central, capturando a luz de maneira deslumbrante. Seja como uma expressão de amor ou como um toque de elegância no seu dia a dia, este anel é uma escolha distinta. Adquira agora e permita que o "Anel de Prata Fina com Brilho Solitário em 925" adicione um toque de brilho e classe à sua coleção de joias.',
        price: 760.00,
        poster: './imgs/aneis/anel2.png',
        category: 'anel',
    },
    {
        id: 19,
        title: 'Pingente Prata Luxo',
        subtitle: 'Pingente personalizado de luxo em prata topázios',
        description: 'Celebre momentos especiais com o "Pingente Personalizado de Luxo em Prata com Topázios". Esta peça exclusiva é uma expressão de elegância personalizada, unindo a nobreza da prata ao brilho cativante dos topázios. O toque personalizado permite que você crie uma joia única, adicionando um significado especial à sua coleção. O design luxuoso e os topázios estrategicamente posicionados conferem um charme refinado, tornando este pingente perfeito para ser usado com um colar de sua escolha. Adquira agora e eternize momentos preciosos com o "Pingente Personalizado de Luxo em Prata com Topázios", uma joia que reflete a singularidade de cada história.',
        price: 340.00,
        poster: './imgs/pingentes/p4.png',
        category: 'pingente',
    },
    {
        id: 20,
        title: 'Pulseira Charmosa',
        subtitle: 'Pulseira charmosa em prata e topázios, 20cm',
        description: 'Encante-se com a "Pulseira Charmosa em Prata e Topázios, 20cm". Esta pulseira é uma fusão de charme e elegância, combinando a beleza clássica da prata com o brilho cativante dos topázios. Com um comprimento de 20cm, ela envolve o pulso com graciosidade, adicionando um toque de encanto a qualquer conjunto. Os topázios estrategicamente cravejados conferem um brilho sutil e uma aura encantadora à peça. Seja para um evento especial ou para elevar o seu estilo diário, esta pulseira é a escolha perfeita para quem busca uma joia que harmoniza charme e sofisticação de maneira excepcional. Adquira agora e deixe-se envolver pela beleza atemporal da "Pulseira Charmosa em Prata e Topázios, 20cm".',
        price: 430.00,
        poster: './imgs/pulseiras/pulseira3.png',
        category: 'pulseira', 
    },
    {
        id: 21,
        title: 'Anel Deluxe Solitário',
        subtitle: 'Anel deluxe solitário em prata 925',
        description: 'Eleve sua sofisticação com o "Anel Deluxe Solitário em Prata 925". Esta joia exibe um design refinado que combina a pureza da prata 925 com a elegância atemporal de um solitário. O anel destaca-se pela sua simplicidade luxuosa, destacando o brilho singular da gema central de maneira cativante. Seja como uma declaração de estilo ou como um símbolo de significado pessoal, este anel deluxe é uma escolha sublime. Adquira agora e permita que o "Anel Deluxe Solitário em Prata 925" adicione um toque de classe e brilho à sua coleção de joias.',
        price: 540.00,
        poster: './imgs/aneis/anel8.png',
        category: 'anel',
    },
    {
        id: 22,
        title: 'Brinco Elegância Topázios',
        subtitle: 'Brinco de prata topázios e brilho, puro requinte',
        description: 'Adorne-se com o "Brinco de Prata com Topázios e Brilho", uma verdadeira expressão de puro requinte. Este par de brincos combina a elegância clássica da prata com o brilho radiante dos topázios, criando uma joia que personifica sofisticação. O design cuidadosamente elaborado destaca-se pela sua simplicidade refinada, adicionando um toque de glamour discreto e atemporal ao seu visual. Seja para uma ocasião especial ou para elevar o seu estilo cotidiano, estes brincos são a escolha perfeita para quem busca uma joia que harmoniza requinte e brilho de maneira excepcional. Adquira agora e permita que o "Brinco de Prata com Topázios e Brilho" eleve a sua elegância a novos patamares de estilo.',
        price: 470.00,
        poster: './imgs/brincos/brinco4.png',
        category: 'brinco',
    },
    {
        id: 23,
        title: 'Colar Quadricular Luxuoso',
        subtitle: 'Colar quadricular luxuoso com pingente e brilho radiante',
        description: 'Destaque-se com o "Colar Quadricular Luxuoso com Pingente e Brilho Radiante", uma peça que personifica o luxo e a elegância. Este colar exibe um design moderno e quadricular, enriquecido com um pingente que irradia um brilho radiante. A combinação de detalhes finamente trabalhados e o brilho cativante elevam este acessório a um nível de sofisticação incomparável. Seja para uma ocasião especial ou para adicionar um toque de glamour ao seu visual diário, este colar é a escolha perfeita para quem busca uma joia que harmoniza estilo contemporâneo e requinte. Adquira agora e permita que o "Colar Quadricular Luxuoso com Pingente e Brilho Radiante" realce sua beleza com um toque de brilho e luxo.',
        price: 540.00,
        poster: './imgs/colares/colar3.png',
        category: 'colar',
    },
    {
        id: 24,
        title: 'Pingente Exclusivo',
        subtitle: 'Pingente personalizado exclusivo em prata topázios para colar',
        description: 'Celebre momentos únicos com o "Pingente Personalizado Exclusivo em Prata com Topázios para Colar". Esta joia exclusiva é uma expressão de singularidade e elegância personalizada, unindo a nobreza da prata ao brilho cativante dos topázios. O toque personalizado permite que você crie uma peça única, adicionando um significado especial à sua coleção de joias. O design exclusivo e os topázios estrategicamente posicionados conferem um charme refinado, tornando este pingente perfeito para ser usado como uma representação única de quem você é. Adquira agora e eternize momentos preciosos com o "Pingente Personalizado Exclusivo em Prata com Topázios para Colar".',
        price: 320.00,
        poster: './imgs/pingentes/p5.png',
        category: 'pingente',
    },
    {
        id: 25,
        title: 'Pulseira Elegância Suprema',
        subtitle: 'Pulseira elegância suprema em prata e topázios, 20cm',
        description: 'Adorne seu pulso com a "Pulseira Elegância Suprema em Prata e Topázios, 20cm". Esta pulseira é uma ode à sofisticação, combinando a pureza da prata com o brilho irresistível dos topázios. Com um comprimento de 20cm, ela envolve seu pulso com graciosidade, adicionando um toque de elegância suprema a qualquer conjunto. Os topázios estrategicamente cravejados conferem um brilho sutil e uma aura encantadora à peça. Seja para uma ocasião especial ou para elevar o seu estilo diário, esta pulseira é a escolha perfeita para quem busca uma joia que harmoniza charme e sofisticação de maneira excepcional. Adquira agora e permita que a "Pulseira Elegância Suprema em Prata e Topázios, 20cm" eleve sua beleza a novas alturas de refinamento.',
        price: 440.00,
        poster: './imgs/pulseiras/pulseira4.png',
        category: 'pulseira',
    },
    {
        id: 26,
        title: 'Anel Radiante Deluxe',
        subtitle: 'Anel radiante deluxe de brilho solitário em prata 925',
        description: 'Experimente o esplendor da elegância com o "Anel Radiante Deluxe de Brilho Solitário em Prata 925". Esta joia excepcional combina a pureza da prata 925 com o brilho cativante de um solitário, criando uma peça que é verdadeiramente radiante. O design deluxe destaca-se pela sua simplicidade luxuosa, colocando em foco a gema central de maneira deslumbrante. Seja para uma ocasião especial ou para adicionar um toque de glamour ao seu dia a dia, este anel é a escolha perfeita para quem busca uma joia que harmoniza classe e brilho de maneira extraordinária. Adquira agora e permita que o "Anel Radiante Deluxe de Brilho Solitário em Prata 925" adicione um toque de sofisticação superior à sua coleção de joias.',
        price: 560.00,
        poster: './imgs/aneis/anel3.png',
        category: 'anel',
    },
    {
        id: 27,
        title: 'Brinco Sofisticado',
        subtitle: 'Brinco sofisticado de prata topázios e brilho, pura elegância',
        description: 'Emane sofisticação com o "Brinco Sofisticado de Prata com Topázios e Brilho", uma joia que personifica pura elegância. Este par de brincos une a nobreza da prata ao esplendor cativante dos topázios, criando uma peça que é simultaneamente refinada e deslumbrante. O design cuidadosamente elaborado destaca-se pela sua simplicidade requintada, adicionando um toque de glamour discreto e atemporal ao seu visual. Seja para uma ocasião especial ou para elevar o seu estilo diário, estes brincos são a escolha perfeita para quem busca uma joia que harmoniza sofisticação e brilho de maneira excepcional. Adquira agora e permita que o "Brinco Sofisticado de Prata com Topázios e Brilho" eleve a sua elegância a novos patamares de estilo.',
        price: 480.00,
        poster: './imgs/brincos/brinco5.png',
        category: 'brinco',
    },
    {
        id: 28,
        title: 'Colar Quadricular Exclusivo',
        subtitle: 'Colar quadricular exclusivo com pingente e brilho radiante',
        description: 'Destaque-se com o "Colar Quadricular Exclusivo com Pingente e Brilho Radiante", uma peça única que personifica exclusividade e sofisticação. Este colar exibe um design quadricular moderno, enriquecido com um pingente que irradia um brilho radiante. A combinação de detalhes finamente trabalhados e o brilho cativante elevam este acessório a um nível de estilo incomparável. Seja para uma ocasião especial ou para adicionar um toque de glamour ao seu visual diário, este colar é a escolha perfeita para quem busca uma joia que harmoniza estilo contemporâneo e requinte exclusivo. Adquira agora e permita que o "Colar Quadricular Exclusivo com Pingente e Brilho Radiante" realce sua beleza com um toque de brilho e distinção.',
        price: 560.00,
        poster: './imgs/colares/colar4.png',
        category: 'colar',
    },
    {
        id: 29,
        title: 'Pingente Charmoso Deluxe',
        subtitle: 'Pingente charmoso deluxe em prata topázios para colar',
        description: 'Eleve o encanto com o "Pingente Charmoso Deluxe em Prata com Topázios para Colar". Esta joia exala charme e sofisticação, combinando a nobreza da prata com o brilho cativante dos topázios. O design deluxe destaca-se pela sua elegância refinada, proporcionando um toque de glamour que complementa qualquer colar. Os topázios estrategicamente posicionados conferem um brilho sutil e uma aura encantadora à peça. Seja como um presente especial ou como um toque refinado para o seu próprio estilo, este pingente é a escolha perfeita para quem busca uma joia que harmoniza charme e elegância de maneira extraordinária. Adquira agora e permita que o "Pingente Charmoso Deluxe em Prata com Topázios para Colar" adicione um toque de luxo à sua coleção de acessórios.',
        price: 330.00,
        poster: './imgs/pingentes/p6.png',
        category: 'pingente',
    },
    {
        id: 30,
        title: 'Pulseira Glamour',
        subtitle: 'Pulseira glamour em prata e topázios, 20cm',
        description: 'Envolva-se em pura sofisticação com a "Pulseira Glamour em Prata e Topázios, 20cm". Esta pulseira é uma expressão de elegância refinada, combinando a beleza clássica da prata com o brilho cativante dos topázios. Com um comprimento de 20cm, ela abraça o pulso com graciosidade, adicionando um toque de glamour a qualquer conjunto. Os topázios estrategicamente cravejados conferem um brilho sutil e uma aura encantadora à peça. Seja para uma ocasião especial ou para elevar o seu estilo diário, esta pulseira é a escolha perfeita para quem busca uma joia que harmoniza charme e sofisticação de maneira excepcional. Adquira agora e permita que a "Pulseira Glamour em Prata e Topázios, 20cm" eleve sua beleza a novos patamares de requinte.',
        price: 410.00,
        poster: './imgs/pulseiras/pulseira5.png',
        category: 'pulseira',
    },
    {
        id: 31,
        title: 'Anel Solitário Premium',
        subtitle: 'Ane solitário premium de brilho em prata 925',
        description: 'Experimente o esplendor da elegância com o "Anel Radiante Deluxe de Brilho Solitário em Prata 925". Esta joia excepcional combina a pureza da prata 925 com o brilho cativante de um solitário, criando uma peça que é verdadeiramente radiante. O design deluxe destaca-se pela sua simplicidade luxuosa, colocando em foco a gema central de maneira deslumbrante. Seja para uma ocasião especial ou para adicionar um toque de glamour ao seu dia a dia, este anel é a escolha perfeita para quem busca uma joia que harmoniza classe e brilho de maneira extraordinária. Adquira agora e permita que o "Anel Radiante Deluxe de Brilho Solitário em Prata 925" adicione um toque de sofisticação superior à sua coleção de joias.',
        price: 560.00,
        poster: './imgs/aneis/anel4.png',
        category: 'anel',
    },
    {
        id: 32,
        title: 'Brinco Luxuoso Elegância',
        subtitle: 'Brinco luxuoso de prata topázios e brilho, puro requinte',
        description: 'Adorne-se com o "Brinco de Prata com Topázios e Brilho", uma verdadeira expressão de puro requinte. Este par de brincos combina a elegância clássica da prata com o brilho radiante dos topázios, criando uma joia que personifica sofisticação. O design cuidadosamente elaborado destaca-se pela sua simplicidade refinada, adicionando um toque de glamour discreto e atemporal ao seu visual. Seja para uma ocasião especial ou para elevar o seu estilo cotidiano, estes brincos são a escolha perfeita para quem busca uma joia que harmoniza requinte e brilho de maneira excepcional. Adquira agora e permita que o "Brinco de Prata com Topázios e Brilho" eleve a sua elegância a novos patamares de estilo.',
        price: 490.00,
        poster: './imgs/brincos/brinco6.png',
        category: 'brinco',
    },
    {
        id: 33,
        title: 'Colar Quadricular Deluxe',
        subtitle: 'Colar quadricular radiante deluxe com pingente e brilho',
        description: 'Faça uma declaração de estilo com o "Colar Estiloso com Pingente Quadricular e Brilho". Este colar cativante combina moda e sofisticação, apresentando um pingente quadricular que incorpora um brilho encantador. O design estiloso deste colar é marcado pela fusão de linhas modernas e elegância clássica, proporcionando um toque contemporâneo à sua coleção de joias. Seja para realçar seu visual casual ou adicionar um elemento de destaque a uma ocasião especial, este colar é a escolha perfeita. Adquira agora e deixe que o "Colar Estiloso com Pingente Quadricular e Brilho" eleve o seu estilo a novas alturas de glamour e sofisticação.',
        price: 580.00,
        poster: './imgs/colares/colar5.png',
        category: 'colar',
    },
    {
        id: 34,
        title: 'Pingente Exclusivo de Luxo',
        subtitle: 'Pingente exclusivo de luxo em prata topázios para colar',
        description: 'Adicione um toque de requinte ao seu visual com o "Pingente Deluxe em Prata com Topázios para Colar". Esta joia exuberante é uma expressão de luxo e sofisticação, unindo a pureza da prata ao brilho deslumbrante dos topázios. O design deluxe deste pingente destaca-se pela sua elegância atemporal e pelos detalhes finamente trabalhados. Seja usado como um ponto focal em um colar ou combinado com outras peças, este pingente é a escolha ideal para quem busca uma joia que emana estilo e distinção. Adquira agora e permita que o "Pingente Deluxe em Prata com Topázios para Colar" eleve o seu visual a novos patamares de elegância.',
        price: 350.00,
        poster: './imgs/pingentes/p7.png',
        category: 'pingente',
    },
    {
        id: 35,
        title: 'Pulseira Charmosa Deluxe',
        subtitle: 'Pulseira charmosa deluxe em prata e topázios, 20cm',
        description: 'Adorne seu pulso com a "Pulseira Elegância Suprema em Prata e Topázios, 20cm". Esta pulseira é uma ode à sofisticação, combinando a pureza da prata com o brilho irresistível dos topázios. Com um comprimento de 20cm, ela envolve seu pulso com graciosidade, adicionando um toque de elegância suprema a qualquer conjunto. Os topázios estrategicamente cravejados conferem um brilho sutil e uma aura encantadora à peça. Seja para uma ocasião especial ou para elevar o seu estilo diário, esta pulseira é a escolha perfeita para quem busca uma joia que harmoniza charme e sofisticação de maneira excepcional. Adquira agora e permita que a "Pulseira Elegância Suprema em Prata e Topázios, 20cm" eleve sua beleza a novas alturas de refinamento.',
        price: 430.00,
        poster: './imgs/pulseiras/pulseira6.png',
        category: 'pulseira',
    },
    {
        id: 36,
        title: 'Anel Brilhante Deluxe',
        subtitle: 'Anel brilhante deluxe de brilho solitário em prata 925',
        description: 'Deixe-se envolver pela luminosidade radiante do "Anel Solitário de Brilho em Prata 925". Este anel é uma expressão de singularidade e elegância, unindo a beleza intemporal da prata 925 ao brilho solitário que captura a luz de maneira envolvente. O design radiante destaca a gema central com um esplendor cativante, tornando este anel uma peça que brilha tanto em ocasiões especiais quanto no dia a dia. Adquira agora e permita que o "Anel Radiante de Brilho Solitário em Prata 925" eleve seu estilo a novos patamares de sofisticação e luminosidade.',
        price: 580.00,
        poster: './imgs/aneis/anel5.png',
        category: 'anel',
    },
    {
        id: 37,
        title: 'Brinco Elegância Suprema',
        subtitle: 'Brinco elegância suprema de prata topázios e brilho',
        description: 'Adorne-se com o "Brinco de Prata com Topázios e Brilho", uma verdadeira expressão de puro requinte. Este par de brincos combina a elegância clássica da prata com o brilho radiante dos topázios, criando uma joia que personifica sofisticação. O design cuidadosamente elaborado destaca-se pela sua simplicidade refinada, adicionando um toque de glamour discreto e atemporal ao seu visual. Seja para uma ocasião especial ou para elevar o seu estilo cotidiano, estes brincos são a escolha perfeita para quem busca uma joia que harmoniza requinte e brilho de maneira excepcional. Adquira agora e permita que o "Brinco de Prata com Topázios e Brilho" eleve a sua elegância a novos patamares de estilo.',
        price: 500.00,
        poster: './imgs/brincos/brinco7.png',
        category: 'brinco',
    },
    {
        id: 38,
        title: 'Colar Quadricular',
        subtitle: 'Colar quadricular glamouroso com pingente e brilho intenso',
        description: 'Faça uma declaração de estilo com o "Colar Quadricular Brilhante com Pingente". Este colar encantador combina um design quadricular moderno com um brilho luminoso, criando uma peça que é ao mesmo tempo contemporânea e elegante. O pingente adiciona um toque especial, destacando-se no padrão quadricular com um brilho cativante. Seja para realçar seu visual casual ou adicionar um toque de sofisticação a uma ocasião especial, este colar é a escolha perfeita. Adquira agora e permita que o "Colar Quadricular Brilhante com Pingente" eleve o seu estilo a novas alturas de glamour e modernidade.',
        price: 590.00,
        poster: './imgs/colares/colar6.png',
        category: 'colar',
    },
    {
        id: 39,
        title: 'Pingente Deluxe Charmoso',
        subtitle: 'Pingente deluxe charmoso em prata topázios para colar',
        description: 'Explore a arte da personalização e adicione um toque único à sua coleção de joias com nosso "Pingente Personalizável em Prata com Topázios para Colar". Este pingente excepcional é mais do que uma peça de joia; é uma expressão personalizada do seu estilo e individualidade. Confeccionado em prata de alta qualidade, o pingente exala elegância e durabilidade. A beleza dos topázios cuidadosamente cravados adiciona um toque de brilho sutil, capturando a luz de maneira encantadora. O destaque verdadeiramente especial deste pingente é a oportunidade de personalização. Adicione um toque pessoal escolhendo um design único, uma inicial ou até mesmo uma data significativa. Seja para celebrar uma ocasião especial ou como um presente pensado, este pingente personalizável é uma maneira extraordinária de eternizar memórias e expressar sua singularidade. Use-o com um colar de sua escolha para criar uma peça única que conte sua história. Com o "Pingente Personalizável em Prata com Topázios para Colar", você não está apenas usando uma joia, está usando uma lembrança personalizada e preciosa. Encomende agora e dê um toque pessoal à sua coleção de acessórios.',
        price: 340.00,
        poster: './imgs/pingentes/p8.png',
        category: 'pingente',
    },
    {
        id: 40,
        title: 'Pulseira Luxo Supremo',
        subtitle: 'Pulseira luxo supremo em prata e topázios, 20cm',
        description: 'Eleve sua sofisticação com a "Pulseira Elegante em Prata e Topázios", uma joia que combina elegância e brilho de forma excepcional. Confeccionada em prata de alta qualidade, esta pulseira destaca-se pela harmoniosa combinação de seus elos delicados e topázios deslumbrantes. Com um comprimento de 20cm, ela envolve seu pulso com graça e estilo. Seja para ocasiões formais ou para adicionar um toque de refinamento ao seu visual diário, esta pulseira é a escolha perfeita. Deixe-se envolver pela beleza atemporal da prata e pelos centelhantes topázios, fazendo desta pulseira uma expressão luminosa da sua elegância única. Adquira agora e realce sua coleção de joias com esse símbolo de sofisticação.',
        price: 450.00,
        poster: './imgs/pulseiras/pulseira7.png',
        category: 'pulseira',
    },
    {
        id: 41,
        title: 'Anel Radiante Elegante',
        subtitle: 'Anel radiante elegante de brilho solitário em prata 925',
        description: 'Deixe-se envolver pela luminosidade radiante do "Anel Solitário de Brilho em Prata 925". Este anel é uma expressão de singularidade e elegância, unindo a beleza intemporal da prata 925 ao brilho solitário que captura a luz de maneira envolvente. O design radiante destaca a gema central com um esplendor cativante, tornando este anel uma peça que brilha tanto em ocasiões especiais quanto no dia a dia. Adquira agora e permita que o "Anel Radiante de Brilho Solitário em Prata 925" eleve seu estilo a novos patamares de sofisticação e luminosidade.',
        price: 600.00,
        poster: './imgs/aneis/anel6.png',
        category: 'anel',
    },
    {
        id: 42,
        title: 'Brinco Deluxe Glamour',
        subtitle: 'Brinco deluxe glamour de prata topázios e brilho',
        description: 'Adorne-se com o "Brinco de Prata com Topázios e Brilho", uma verdadeira expressão de puro requinte. Este par de brincos combina a elegância clássica da prata com o brilho radiante dos topázios, criando uma joia que personifica sofisticação. O design cuidadosamente elaborado destaca-se pela sua simplicidade refinada, adicionando um toque de glamour discreto e atemporal ao seu visual. Seja para uma ocasião especial ou para elevar o seu estilo cotidiano, estes brincos são a escolha perfeita para quem busca uma joia que harmoniza requinte e brilho de maneira excepcional. Adquira agora e permita que o "Brinco de Prata com Topázios e Brilho" eleve a sua elegância a novos patamares de estilo.',
        price: 520.00,
        poster: './imgs/brincos/brinco8.png',
        category: 'brinco',
    },
    {
        id: 43,
        title: 'Colar Quadricular Radiante',
        subtitle: 'Colar quadricular radiante supremo com pingente e brilho',
        description: 'Faça uma declaração de estilo com o "Colar Quadricular Brilhante com Pingente". Este colar encantador combina um design quadricular moderno com um brilho luminoso, criando uma peça que é ao mesmo tempo contemporânea e elegante. O pingente adiciona um toque especial, destacando-se no padrão quadricular com um brilho cativante. Seja para realçar seu visual casual ou adicionar um toque de sofisticação a uma ocasião especial, este colar é a escolha perfeita. Adquira agora e permita que o "Colar Quadricular Brilhante com Pingente" eleve o seu estilo a novas alturas de glamour e modernidade.',
        price: 620.00,
        poster: './imgs/colares/colar7.png',
        category: 'colar',
    },
    {
        id: 44,
        title: 'Pingente Charmoso',
        subtitle: 'Pingente charmoso supremo em prata topázios para colar',
        description: 'Eleve o encanto com o "Pingente Charmoso Deluxe em Prata com Topázios para Colar". Esta joia exala charme e sofisticação, combinando a nobreza da prata com o brilho cativante dos topázios. O design deluxe destaca-se pela sua elegância refinada, proporcionando um toque de glamour que complementa qualquer colar. Os topázios estrategicamente posicionados conferem um brilho sutil e uma aura encantadora à peça. Seja como um presente especial ou como um toque refinado para o seu próprio estilo, este pingente é a escolha perfeita para quem busca uma joia que harmoniza charme e elegância de maneira extraordinária. Adquira agora e permita que o "Pingente Charmoso Deluxe em Prata com Topázios para Colar" adicione um toque de luxo à sua coleção de acessórios.',
        price: 360.00,
        poster: './imgs/pingentes/p9.png',
        category: 'pingente',
    },
    {
        id: 45,
        title: 'Pulseira Deluxe Brilhante',
        subtitle: 'Pulseira deluxe brilhante em prata e topázios, 20cm',
        description: 'Deslumbre com a "Pulseira deluxe e brilhante em prata e topázios, 20cm de Elegância". Esta pulseira exala sofisticação, combinando a pureza da prata com o brilho cativante dos topázios. Com seu comprimento de 20cm, a pulseira envolve o pulso com graciosidade, acrescentando um toque de elegância refinada. Os topázios estrategicamente cravejados conferem um charme sutil, destacando-se como símbolos de refinamento e beleza. Seja para um evento especial ou para elevar o seu estilo cotidiano, esta pulseira é a escolha perfeita para quem busca uma joia que une estilo e elegância de maneira única. Adquira agora e deixe-se envolver pela beleza atemporal da "Pulseira em Prata e Topázios, 20cm de Elegância".',
        price: 470.00,
        poster: './imgs/pulseiras/pulseira8.png',
        category: 'pulseira',
    },
    {
        id: 46,
        title: 'Anel Supremo Deluxe',
        subtitle: 'Anel supremo deluxe de brilho solitário em prata 925',
        description:'Descubra a expressão máxima de luxo com nosso "Anel Solitário de Luxo em Prata 925". Este anel excepcional combina a beleza intemporal da prata fina 925 com o esplendor de um solitário brilhante, criando uma peça que é ao mesmo tempo deslumbrante e elegante. O design cuidadosamente elaborado destaca o brilho singular da gema central, que reflete a luz de maneira cativante, enchendo o ambiente com uma luminosidade única. A prata 925 confere ao anel uma qualidade excepcional, assegurando durabilidade e um acabamento impecável. Seja como uma declaração de compromisso, presente especial ou simplesmente para elevar seu estilo cotidiano, este anel solitário é a escolha perfeita. Sua elegância discreta e design atemporal fazem dele uma joia versátil que pode ser apreciada em todas as ocasiões. Viva a experiência de usar uma peça que reflete seu gosto refinado e celebra a singularidade do momento. Eleve seu estilo com o "Anel Solitário de Luxo em Prata 925" – uma joia que transcende o tempo com sua beleza clássica e atemporal. Adquira o seu agora e adicione um toque de luxo à sua coleção de acessórios.',
        price: 620.00,
        poster: './imgs/aneis/anel7.png',
        category: 'anel',
    },
    {
        id: 47,
        title: 'Brinco Radiante Glamour',
        subtitle: 'Brinco radiante glamour de prata topázios e brilho',
        description: 'Adorne-se com o "Brinco de Prata com Topázios e Brilho", uma verdadeira expressão de puro requinte. Este par de brincos combina a elegância clássica da prata com o brilho radiante dos topázios, criando uma joia que personifica sofisticação. O design cuidadosamente elaborado destaca-se pela sua simplicidade refinada, adicionando um toque de glamour discreto e atemporal ao seu visual. Seja para uma ocasião especial ou para elevar o seu estilo cotidiano, estes brincos são a escolha perfeita para quem busca uma joia que harmoniza requinte e brilho de maneira excepcional. Adquira agora e permita que o "Brinco de Prata com Topázios e Brilho" eleve a sua elegância a novos patamares de estilo.',
        price: 520.00,
        poster: './imgs/brincos/brinco9.png',
        category: 'brinco',
    },
    {
        id: 48,
        title: 'Colar Luxo Supreme',
        subtitle: 'Colar quadricular luxo supreme com pingente e brilho intenso',
        description: 'Faça uma declaração de estilo com o "Colar Estiloso com Pingente Quadricular e Brilho". Este colar cativante combina moda e sofisticação, apresentando um pingente quadricular que incorpora um brilho encantador. O design estiloso deste colar é marcado pela fusão de linhas modernas e elegância clássica, proporcionando um toque contemporâneo à sua coleção de joias. Seja para realçar seu visual casual ou adicionar um elemento de destaque a uma ocasião especial, este colar é a escolha perfeita. Adquira agora e deixe que o "Colar Estiloso com Pingente Quadricular e Brilho" eleve o seu estilo a novas alturas de glamour e sofisticação.',
        price: 640.00,
        poster: './imgs/colares/colar8.png',
        category: 'colar',
    },                                                                                                                                                                                                          
    {
        id: 49,
        title: 'Pingente Deluxe Exclusivo',
        subtitle: 'Pingente deluxe exclusivo em prata topázios para colar',
        description: 'Explore a arte da personalização e adicione um toque único à sua coleção de joias com nosso "Pingente Personalizável em Prata com Topázios para Colar". Este pingente excepcional é mais do que uma peça de joia; é uma expressão personalizada do seu estilo e individualidade. Confeccionado em prata de alta qualidade, o pingente exala elegância e durabilidade. A beleza dos topázios cuidadosamente cravados adiciona um toque de brilho sutil, capturando a luz de maneira encantadora. O destaque verdadeiramente especial deste pingente é a oportunidade de personalização. Adicione um toque pessoal escolhendo um design único, uma inicial ou até mesmo uma data significativa. Seja para celebrar uma ocasião especial ou como um presente pensado, este pingente personalizável é uma maneira extraordinária de eternizar memórias e expressar sua singularidade. Use-o com um colar de sua escolha para criar uma peça única que conte sua história. Com o "Pingente Personalizável em Prata com Topázios para Colar", você não está apenas usando uma joia, está usando uma lembrança personalizada e preciosa. Encomende agora e dê um toque pessoal à sua coleção de acessórios.',
        price: 380.00,
        poster: './imgs/pingentes/p10.png',
        category: 'pingente',
    },
    {
        id: 50,
        title: 'Pulseira Elegância Supreme',
        subtitle: 'Pulseira elegância supreme em prata e topázios, 20cm',
        description: 'Encante-se com a "Pulseira Elegância Supreme, 20cm". Esta pulseira é uma fusão de charme e elegância, combinando a beleza clássica da prata com o brilho cativante dos topázios. Com um comprimento de 20cm, ela envolve o pulso com graciosidade, adicionando um toque de encanto a qualquer conjunto. Os topázios estrategicamente cravejados conferem um brilho sutil e uma aura encantadora à peça. Seja para um evento especial ou para elevar o seu estilo diário, esta pulseira é a escolha perfeita para quem busca uma joia que harmoniza charme e sofisticação de maneira excepcional. Adquira agora e deixe-se envolver pela beleza atemporal da "Pulseira Charmosa em Prata e Topázios, 20cm".',
        price: 490.00,
        poster: './imgs/pulseiras/pulseira9.png',
        category: 'pulseira',
    },
];
